site_name: My Docs
repo_url: https://github.com/BuckyI/Notes
theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes 
    - header.autohide

nav:
  - index.md

extra_css:
  - stylesheets/extra.css